"""
Django settings for rentalution project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from datetime import timedelta
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir))))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SILENCED_SYSTEM_CHECKS = ['models.W042']
ENVIRONMENT_NAME = os.environ.get('ENVIRONMENT_NAME', 'Development')
ENVIRONMENT_COLOR = os.environ.get('ENVIRONMENT_COLOR', 'blue')
SITE_URL = os.environ.get('SITE_URL', 'https://rentalution.co.uk')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@rentalution.co.uk')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('RENTALUTION_SECRET_KEY', os.environ.get('DJANGO_SECRET_KEY', ''))

ALLOWED_HOSTS = ['*']

# Cloudflare Turnstile
CLOUDFLARE_TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '')
CLOUDFLARE_TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')

# Avatar generation (Replicate)
AVATAR_GENERATION_ENABLED = os.environ.get('AVATAR_GENERATION_ENABLED', '0') == '1'
REPLICATE_API_TOKEN = os.environ.get('REPLICATE_API_TOKEN', '')
REPLICATE_AVATAR_MODEL_VERSION = os.environ.get('REPLICATE_AVATAR_MODEL_VERSION', '')
REPLICATE_AVATAR_IMAGE_FIELD = os.environ.get('REPLICATE_AVATAR_IMAGE_FIELD', 'image')
REPLICATE_AVATAR_PROMPT_FIELD = os.environ.get('REPLICATE_AVATAR_PROMPT_FIELD', '')
REPLICATE_AVATAR_PROMPT = os.environ.get('REPLICATE_AVATAR_PROMPT', '')
REPLICATE_AVATAR_TIMEOUT_SECONDS = int(os.environ.get('REPLICATE_AVATAR_TIMEOUT_SECONDS', '45'))

MOBILE_VERIFICATION_ENABLED = os.environ.get('MOBILE_VERIFICATION_ENABLED', '1') == '1'
TRANSACTION_LIVE_POLL_SECONDS = max(1, int(os.environ.get('TRANSACTION_LIVE_POLL_SECONDS', '3')))
TRANSACTION_FEEDBACK_WINDOW_DAYS = max(1, int(os.environ.get('TRANSACTION_FEEDBACK_WINDOW_DAYS', '30')))
TRANSACTION_REMINDER_WINDOW_START_HOUR = int(os.environ.get('TRANSACTION_REMINDER_WINDOW_START_HOUR', '9'))
TRANSACTION_REMINDER_WINDOW_END_HOUR = int(os.environ.get('TRANSACTION_REMINDER_WINDOW_END_HOUR', '20'))
TRANSACTION_REMINDER_COUNTERPARTY_EVERY_HOURS = max(1, int(os.environ.get('TRANSACTION_REMINDER_COUNTERPARTY_EVERY_HOURS', '4')))
TRANSACTION_REMINDER_FIRST_SIGNER_EVERY_HOURS = max(1, int(os.environ.get('TRANSACTION_REMINDER_FIRST_SIGNER_EVERY_HOURS', '12')))
TRANSACTION_REMINDER_RETURN_EVERY_HOURS = max(1, int(os.environ.get('TRANSACTION_REMINDER_RETURN_EVERY_HOURS', '4')))
TRANSACTION_REMINDER_FEEDBACK_EVERY_HOURS = max(1, int(os.environ.get('TRANSACTION_REMINDER_FEEDBACK_EVERY_HOURS', '4')))
TRANSACTION_MAJOR_NOTIFICATION_STATUSES = [
    'RAGR',
    'RDAYAWV',
    'RONG',
    'RRTDAYAWV',
    'RRTDPEND',
    'RRTDCON',
    'DREQ',
    'AWFB',
    'FB1SIDE',
    'RCOMP',
    'RCOMP1S',
    'RCMPNFB',
    'CACK',
]
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_VERIFY_SERVICE_SID = os.environ.get('TWILIO_VERIFY_SERVICE_SID', '')

# Stripe Connect
STRIPE_CONNECT_ALLOW_LEGACY_CARD_FALLBACK = os.environ.get('STRIPE_CONNECT_ALLOW_LEGACY_CARD_FALLBACK', '1') == '1'
STRIPE_CONNECT_PUBLIC_KEY = os.environ.get('STRIPE_CONNECT_PUBLIC_KEY', '')
STRIPE_CONNECT_SECRET_KEY = os.environ.get('STRIPE_CONNECT_SECRET_KEY', '')
STRIPE_CONNECT_WEBHOOK_SECRET = os.environ.get('STRIPE_CONNECT_WEBHOOK_SECRET', '')
STRIPE_CONNECT_PLATFORM_ACCOUNT = os.environ.get('STRIPE_CONNECT_PLATFORM_ACCOUNT', '')

# Firebase Cloud Messaging settings.
# HTTP v1 uses OAuth2 via a service account key file.
FCM_PROJECT_ID = os.environ.get('FCM_PROJECT_ID', '')
FCM_SENDER_ID = os.environ.get('FCM_SENDER_ID', '')
_fcm_service_account_file = (os.environ.get('FCM_SERVICE_ACCOUNT_FILE', '') or '').strip()
if _fcm_service_account_file and not os.path.isabs(_fcm_service_account_file):
    _fcm_service_account_file = os.path.abspath(os.path.join(BASE_DIR, _fcm_service_account_file))
FCM_SERVICE_ACCOUNT_FILE = _fcm_service_account_file
# Deprecated: legacy HTTP key (kept for backward compatibility with older env files).
FCM_SERVER_KEY = os.environ.get('FCM_SERVER_KEY', '')

# NPD - added
LOGIN_REDIRECT_URL = "my_rentalution:dashboard"
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

AUTHENTICATION_BACKENDS = [
    'account.backends.EmailAuthBackend',
]

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')
# NPD - finished

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'haystack',
    'mobile_api.apps.MobileApiConfig',
    'navigation.apps.NavigationConfig',
    'pages.apps.PagesConfig',
    'account.apps.AccountConfig',
    'common.apps.CommonConfig',
    'catalog_workflow.apps.CatalogWorkflowConfig',
    'my_rentalution.apps.MySharingHubConfig',
    'transaction.apps.TransactionConfig',
    'friends.apps.FriendsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'cookielaw',
    'sorl.thumbnail',
    'simple_history',
    'django.contrib.humanize',
    # 'django_otp',
    # 'django_otp.plugins.otp_totp',
    'admin_honeypot',
    'memcache_status',
    'django_summernote.apps.DjangoSummernoteConfig',
    # 'floppyforms',
    # 'material',
    # 'material.frontend',
]

MIDDLEWARE = [
    'common.middlewares.AjaxMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'rentalution.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 
            os.path.join(BASE_DIR, 'rentalution/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rentalution.context_processors.from_settings',
                'rentalution.context_processors.top_categories',
                'rentalution.context_processors.transaction_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'rentalution.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'rentalution',
#         'USER': 'rentalution',
#         'PASSWORD': '9bNi8TlgoXp88fds',
#         'HOST': 'localhost', 
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# TODO: not valid for PROD
# https://django-haystack.readthedocs.io/en/master/tutorial.html
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}


# for two factor authentication of Admin
# OTP_TOTP_ISSUER = 'SharingHub'

# Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

BOOTSTRAP4 = {
    'horizontal_label_class': 'col-md-2',
    'horizontal_field_class': 'col-md-10'
}


# Transpact settings
TRANSPACT_WSDL = 'https://www.transpact.com/SecurePartner/Partner.asmx?WSDL'
TRANSPACT_PARTNER_USERNAME = 'neil.daniels@sharing-hub.com'
TRANSPACT_PARTNER_PASSWORD = '10mC9wRrX'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
}
