# Generated by Django 4.2.27 on 2026-04-21 21:46

import account.validators
import common.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(validators=[account.validators.MinAgeValidator])),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(max_length=255, verbose_name='Town/City')),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Cached latitude from postcode lookup', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Cached longitude from postcode lookup', max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, upload_to=common.helpers.RandomFileName('users/'))),
                ('user_rating', models.FloatField(default=0)),
                ('user_successful_txns', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('user_failed_txns', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
