# Generated by Django 4.2.27 on 2026-04-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_mobile_and_registrationverification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registrationverification',
            new_name='account_reg_email_25dc02_idx',
            old_name='account_regi_email_a878fd_idx',
        ),
        migrations.RenameIndex(
            model_name='registrationverification',
            new_name='account_reg_expires_106236_idx',
            old_name='account_regi_expires_c64689_idx',
        ),
    ]
