# Generated by Django 4.2.27 on 2026-04-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_registrationverification_house_name_number'),
        ('account', '0003_rename_account_regi_email_a878fd_idx_account_reg_email_25dc02_idx_and_more'),
    ]

    operations = [
    ]
