# Generated by Django 4.2.27 on 2026-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_20260426_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationverification',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
