# Generated by Django 4.2.27 on 2026-05-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_registrationverification_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
