# Generated by Django 4.2.27 on 2026-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_mobile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
    ]
