# Generated by Django 4.2.27 on 2026-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_address_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_identity_verification_id',
            field=models.CharField(blank=True, help_text='Stripe Identity verification session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_identity_verified',
            field=models.BooleanField(default=False, help_text='Whether user has completed KYC verification via Stripe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_identity_verified_at',
            field=models.DateTimeField(blank=True, help_text='When user completed KYC verification', null=True),
        ),
    ]
