# Generated by Django 4.2.27 on 2026-05-10 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_profile_stripe_identity_verification_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_identity_verification_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_identity_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_identity_verified_at',
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe PaymentMethod ID', max_length=100, unique=True)),
                ('stripe_setup_intent_id', models.CharField(blank=True, help_text='Stripe SetupIntent ID used to create this payment method', max_length=100)),
                ('card_brand', models.CharField(default='Card', help_text='Card brand (Visa, Mastercard, etc.)', max_length=20)),
                ('card_last4', models.CharField(help_text='Last 4 digits of card', max_length=4)),
                ('is_default', models.BooleanField(default=False, help_text='Use this card by default for deposits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
