# Generated by Django 4.2.27 on 2026-05-14 11:00

import common.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_profile_stripe_identity_verification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationverification',
            name='image',
            field=models.ImageField(blank=True, upload_to=common.helpers.RandomFileName('users/')),
        ),
    ]
