# Generated by Django 4.2.27 on 2026-06-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_paymentmethod_card_funding'),
        ('account', '0019_registrationverification_avatar_accessories_color'),
    ]

    operations = [
    ]
