# Generated by Django 4.2.27 on 2026-06-07 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_merge_20260607_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bookings_pending_my_action',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_bookings_pending_other_party',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
