# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_profile_user_bookings_pending_my_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_identity_verification_id',
            field=models.CharField(blank=True, help_text='Stripe Identity verification session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_identity_verified',
            field=models.BooleanField(default=False, help_text='Whether user has completed KYC verification via Stripe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_identity_verified_at',
            field=models.DateTimeField(blank=True, help_text='When user completed KYC verification', null=True),
        ),
    ]
