# Generated by Django 4.2.27 on 2026-04-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fineness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precious_metal_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
