# Generated by Django 4.2.27 on 2026-04-23 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_delete_postage_remove_product_fineness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='additional_comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='collection_policy',
            field=models.CharField(choices=[('MC', 'Must collect'), ('WD', 'Will deliver'), ('EI', 'Collect or deliver')], default='MC', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='delivery_cost',
            field=models.FloatField(blank=True, help_text='Delivery cost (£), if applicable', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='deposit',
            field=models.FloatField(blank=True, help_text='Refundable deposit amount (£)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='mates_deposit',
            field=models.FloatField(blank=True, help_text='Reduced deposit for friends', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='mates_rates',
            field=models.FloatField(blank=True, help_text='Discounted price per day for friends', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_policy',
            field=models.CharField(choices=[('MC', 'Must collect'), ('WD', 'Will deliver'), ('EI', 'Collect or deliver')], default='MC', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.FloatField(blank=True, help_text='Delivery cost (£), if applicable', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.FloatField(blank=True, help_text='Refundable deposit amount (£)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='mates_deposit',
            field=models.FloatField(blank=True, help_text='Reduced deposit for friends', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='mates_rates',
            field=models.FloatField(blank=True, help_text='Discounted price per day for friends', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='LetPriceBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(help_text='Rental duration in days this rate applies to (e.g. 1, 5, 7, 30)')),
                ('price_per_day', models.FloatField(help_text='Price per day (£) for this duration band', validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bands', to='common.order')),
            ],
            options={
                'ordering': ['duration_days'],
            },
        ),
    ]
