# Generated by Django 4.2.27 on 2026-04-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_historicalorder_additional_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBlockedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('M', 'Manual'), ('B', 'Booked')], default='M', max_length=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='common.order')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('order', 'date')},
            },
        ),
    ]
