# Generated by Django 4.2.27 on 2026-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_orderblockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='collection_details',
            field=models.CharField(blank=True, default='', help_text='e.g. times of collection, address note', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_details',
            field=models.CharField(blank=True, default='', help_text='e.g. times of collection, address note', max_length=200),
        ),
    ]
