# Generated by Django 4.2.27 on 2026-04-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_order_collection_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='max_rental_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of days a borrower can rent this item in one booking', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='max_rental_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of days a borrower can rent this item in one booking', null=True),
        ),
    ]
