# Generated by Django 4.2.27 on 2026-04-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_order_max_rental_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='max_rental_days',
            field=models.PositiveIntegerField(blank=True, default=7, help_text='Maximum number of days a borrower can rent this item in one booking', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='max_rental_days',
            field=models.PositiveIntegerField(blank=True, default=7, help_text='Maximum number of days a borrower can rent this item in one booking', null=True),
        ),
    ]
