# Generated by Django 4.2.27 on 2026-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_order_max_rental_days_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Main image shown in listing thumbnail'),
        ),
    ]
