# Generated by Django 4.2.27 on 2026-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_order_let_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='let_visibility',
            field=models.CharField(choices=[('FRIENDS', 'Let to friends only'), ('PUBLIC', 'Let to public only'), ('BOTH', 'Let to both')], db_index=True, default='BOTH', help_text='Who can see and rent this listing', max_length=8),
        ),
    ]
