# Generated by Django 4.2.27 on 2026-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_categorytag_category_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
