# Generated by Django 4.2.27 on 2026-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='direction',
            field=models.CharField(choices=[('W', 'Wanted'), ('L', 'To Lend')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[('W', 'Wanted'), ('L', 'To Lend')], db_index=True, max_length=1),
        ),
    ]
