# Generated by Django 4.2.27 on 2026-05-09 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_historicalorder_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='risk_rating',
            field=models.PositiveIntegerField(default=0, help_text='Risk rating: 0-25 Low, 26-50 Medium, 51-75 High, 76-100 Very High. Products >75 require KYC verification', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='risk_rating',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Override category risk rating for this product. Leave blank to inherit from category.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
