# Generated by Django 4.2.27 on 2026-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_backfill_categoryattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='collection_policy',
            field=models.CharField(choices=[('MC', 'You must collect'), ('WD', 'Lender will deliver'), ('EI', 'Collection or delivery - To be discussed')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='collection_policy',
            field=models.CharField(choices=[('MC', 'You must collect'), ('WD', 'Lender will deliver'), ('EI', 'Collection or delivery - To be discussed')], default='MC', max_length=2),
        ),
    ]
