# Generated by Django 4.2.27 on 2026-05-30 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_favouriteorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='delivery_cost_per_km',
            field=models.FloatField(blank=True, help_text='Delivery cost per km (£) within the included distance', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='delivery_within_km',
            field=models.PositiveIntegerField(blank=True, help_text='Delivery is charged per km up to this distance', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost_per_km',
            field=models.FloatField(blank=True, help_text='Delivery cost per km (£) within the included distance', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_within_km',
            field=models.PositiveIntegerField(blank=True, help_text='Delivery is charged per km up to this distance', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='delivery_cost',
            field=models.FloatField(blank=True, help_text='Flat delivery fee (£) when the delivery distance is beyond the included range', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.FloatField(blank=True, help_text='Flat delivery fee (£) when the delivery distance is beyond the included range', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
