# Generated by Django 4.2.27 on 2026-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_historicalorder_delivery_cost_per_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='collection_address',
            field=models.CharField(blank=True, default='', help_text='Collection address if different from the home address', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='collection_is_home_address',
            field=models.BooleanField(default=True, help_text='Set this to false if collection happens somewhere other than your home address.'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='collection_postcode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Collection postcode if different from the home address', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_address',
            field=models.CharField(blank=True, default='', help_text='Collection address if different from the home address', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_is_home_address',
            field=models.BooleanField(default=True, help_text='Set this to false if collection happens somewhere other than your home address.'),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_postcode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Collection postcode if different from the home address', max_length=10),
        ),
    ]
