# Generated by Django 4.2.27 on 2026-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_order_verified_users_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='verified_users_only',
            field=models.BooleanField(default=False, help_text='Only users who have completed Stripe identity verification can enquire on this listing.'),
        ),
    ]
