# Generated by Django 4.2.27 on 2026-06-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_alter_sitefailure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='value_source',
            field=models.CharField(choices=[('product', 'Product'), ('listing', 'Listing')], default='product', help_text='Choose whether the value belongs to the product itself or to each individual listing.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='attribute_five_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='attribute_four_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='attribute_one_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='attribute_three_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='attribute_two_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attribute_five_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attribute_four_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attribute_one_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attribute_three_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attribute_two_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
