# Generated by Django 4.2.27 on 2026-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfriendship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
