# Generated by Django 4.2.27 on 2026-04-24 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_add_paused_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBlockedUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blocked_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who performed the block', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ForeignKey(blank=True, db_constraint=False, help_text='User who was blocked', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical blocked user',
                'verbose_name_plural': 'historical blocked users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(help_text='User who performed the block', on_delete=django.db.models.deletion.CASCADE, related_name='users_i_blocked', to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ForeignKey(help_text='User who was blocked', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blocked_by'], name='friends_blo_blocked_f2656b_idx'), models.Index(fields=['blocked_user'], name='friends_blo_blocked_86711a_idx')],
                'unique_together': {('blocked_by', 'blocked_user')},
            },
        ),
    ]
