# Generated by Django 4.2.27 on 2026-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_historicalblockeduser_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='report_flagged',
            field=models.BooleanField(default=False, help_text='Whether this block was reported to admin'),
        ),
        migrations.AddField(
            model_name='historicalblockeduser',
            name='report_flagged',
            field=models.BooleanField(default=False, help_text='Whether this block was reported to admin'),
        ),
    ]
