# Generated by Django 4.2.27 on 2026-04-21 21:46

import common.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import transaction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_passive_description', models.TextField(blank=True, max_length=250)),
                ('transaction_status', models.CharField(choices=[('NEW', 'New'), ('NEWTOUT', 'New Timeout'), ('PAYPROC', 'Awaiting Payment to ESCROW'), ('DELPROC', 'Delivery process pending'), ('CREQ', 'Cancel Requested'), ('CCAN', 'Cancellation reversed'), ('CACK', 'Cancel Accepted'), ('CREF', 'Cancel Refused'), ('DREQ', 'Dispute Request Raised'), ('DRES', 'Dispute Resolved'), ('DTOUT', 'Dispute Timeout'), ('COMP', 'Completed'), ('PEND', 'Pending'), ('PENDTOUT', 'Pending Timeout'), ('RTNPND', 'Return Pending'), ('RTNACK', 'Return Ack'), ('PBOTH', 'Pending term acceptance - both parties'), ('PBUY', 'Pending term acceptance - buyer'), ('PSELL', 'Pending term acceptance - seller'), ('VOID', 'Transaction Voided - terms rejected'), ('ESCROW', 'Funds received and protected in escrow'), ('PNACK', 'Product Not as Advertised'), ('PACK', 'Product Verified OK')], default='NEW', max_length=20, verbose_name='transaction status')),
                ('prev_transaction_status', models.CharField(choices=[('NEW', 'New'), ('NEWTOUT', 'New Timeout'), ('PAYPROC', 'Awaiting Payment to ESCROW'), ('DELPROC', 'Delivery process pending'), ('CREQ', 'Cancel Requested'), ('CCAN', 'Cancellation reversed'), ('CACK', 'Cancel Accepted'), ('CREF', 'Cancel Refused'), ('DREQ', 'Dispute Request Raised'), ('DRES', 'Dispute Resolved'), ('DTOUT', 'Dispute Timeout'), ('COMP', 'Completed'), ('PEND', 'Pending'), ('PENDTOUT', 'Pending Timeout'), ('RTNPND', 'Return Pending'), ('RTNACK', 'Return Ack'), ('PBOTH', 'Pending term acceptance - both parties'), ('PBUY', 'Pending term acceptance - buyer'), ('PSELL', 'Pending term acceptance - seller'), ('VOID', 'Transaction Voided - terms rejected'), ('ESCROW', 'Funds received and protected in escrow'), ('PNACK', 'Product Not as Advertised'), ('PACK', 'Product Verified OK')], default='NEW', max_length=20, verbose_name='previous transaction status')),
                ('payment_status', models.CharField(choices=[('PYNOTSNT', 'Payment Not Sent'), ('PYSNT', 'Payment Sent'), ('PYACK', 'Payment Received'), ('REFREQ', 'Refund Requested'), ('REFREJ', 'Refund Rejected'), ('REFSNT', 'Refund Sent'), ('REFACK', 'Refund Received'), ('PAYTOUT', 'Payment Timeout'), ('REFTOUT', 'Refund Timeout'), ('REFACK', 'Refund Completed'), ('ESCROW', 'Funds received and protected in escrow'), ('FUNDRE', 'Funds released to seller')], default='PYNOTSNT', max_length=20, verbose_name='payment status')),
                ('product_status', models.CharField(choices=[('PNOTSNT', 'Product Not Sent'), ('PSENT', 'Product Sent'), ('PREC', 'Product Received'), ('PNACK', 'Product Not as Advertised'), ('PACK', 'Product Verified OK'), ('PNOTREC', 'Product Not Received'), ('PNOTSNTTOUT', 'Product Not Sent Timeout'), ('PNOTRECTOUT', 'Product Not Received Timeout'), ('PRET', 'Product Returned'), ('PRETACK', 'Product Returned Received'), ('PRETTOUT', 'Product Received Timeout')], default='PNOTSNT', max_length=20, verbose_name='product status')),
                ('transaction_reference', models.CharField(db_index=True, default=transaction.models.unique_txn_ref_generator, max_length=25)),
                ('transpact_text_status', models.CharField(blank=True, max_length=500, null=True)),
                ('transpact_update_datetime', models.DateTimeField(blank=True, null=True)),
                ('transpact_scraped_datetime', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('friend_price', models.FloatField(blank=True, help_text='Special price for friends. If not set, regular price applies to all.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('deposit', models.FloatField(default=0, help_text='Deposit required from non-friends', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('friend_deposit', models.FloatField(blank=True, help_text='Special deposit for friends. If not set, regular deposit applies to all.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('delivery_distance_km', models.PositiveIntegerField(default=10, help_text='Maximum distance in km the lender can deliver/travel', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('total_weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('current_spot_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('price_as_pct_spot_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('created', models.DateField(auto_now_add=True)),
                ('amended', models.DateField(auto_now=True)),
                ('order_aggressive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_order_aggressive', to='common.order')),
                ('order_passive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_order_passive', to='common.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product')),
                ('transaction_status_raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_raised_by', to=settings.AUTH_USER_MODEL)),
                ('user_aggressive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
                ('user_passive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email_to_sender', models.BooleanField(default=False)),
                ('read_by_user_to', models.BooleanField(default=False)),
                ('email_to_recepient', models.BooleanField(default=False)),
                ('include_admin', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMessageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.helpers.RandomFileName('images/txn_msg/'))),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('first_image', models.BooleanField(default=True)),
                ('txn_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txn_msg_img', to='transaction.transactionmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.helpers.RandomFileName('images/transactions/'))),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
                ('transaction_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.transactionfee')),
                ('user_to_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTransactionMessage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('email_to_sender', models.BooleanField(default=False)),
                ('read_by_user_to', models.BooleanField(default=False)),
                ('email_to_recepient', models.BooleanField(default=False)),
                ('include_admin', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transaction.transaction')),
                ('user_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical transaction message',
                'verbose_name_plural': 'historical transaction messages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_passive_description', models.TextField(blank=True, max_length=250)),
                ('transaction_status', models.CharField(choices=[('NEW', 'New'), ('NEWTOUT', 'New Timeout'), ('PAYPROC', 'Awaiting Payment to ESCROW'), ('DELPROC', 'Delivery process pending'), ('CREQ', 'Cancel Requested'), ('CCAN', 'Cancellation reversed'), ('CACK', 'Cancel Accepted'), ('CREF', 'Cancel Refused'), ('DREQ', 'Dispute Request Raised'), ('DRES', 'Dispute Resolved'), ('DTOUT', 'Dispute Timeout'), ('COMP', 'Completed'), ('PEND', 'Pending'), ('PENDTOUT', 'Pending Timeout'), ('RTNPND', 'Return Pending'), ('RTNACK', 'Return Ack'), ('PBOTH', 'Pending term acceptance - both parties'), ('PBUY', 'Pending term acceptance - buyer'), ('PSELL', 'Pending term acceptance - seller'), ('VOID', 'Transaction Voided - terms rejected'), ('ESCROW', 'Funds received and protected in escrow'), ('PNACK', 'Product Not as Advertised'), ('PACK', 'Product Verified OK')], default='NEW', max_length=20, verbose_name='transaction status')),
                ('prev_transaction_status', models.CharField(choices=[('NEW', 'New'), ('NEWTOUT', 'New Timeout'), ('PAYPROC', 'Awaiting Payment to ESCROW'), ('DELPROC', 'Delivery process pending'), ('CREQ', 'Cancel Requested'), ('CCAN', 'Cancellation reversed'), ('CACK', 'Cancel Accepted'), ('CREF', 'Cancel Refused'), ('DREQ', 'Dispute Request Raised'), ('DRES', 'Dispute Resolved'), ('DTOUT', 'Dispute Timeout'), ('COMP', 'Completed'), ('PEND', 'Pending'), ('PENDTOUT', 'Pending Timeout'), ('RTNPND', 'Return Pending'), ('RTNACK', 'Return Ack'), ('PBOTH', 'Pending term acceptance - both parties'), ('PBUY', 'Pending term acceptance - buyer'), ('PSELL', 'Pending term acceptance - seller'), ('VOID', 'Transaction Voided - terms rejected'), ('ESCROW', 'Funds received and protected in escrow'), ('PNACK', 'Product Not as Advertised'), ('PACK', 'Product Verified OK')], default='NEW', max_length=20, verbose_name='previous transaction status')),
                ('payment_status', models.CharField(choices=[('PYNOTSNT', 'Payment Not Sent'), ('PYSNT', 'Payment Sent'), ('PYACK', 'Payment Received'), ('REFREQ', 'Refund Requested'), ('REFREJ', 'Refund Rejected'), ('REFSNT', 'Refund Sent'), ('REFACK', 'Refund Received'), ('PAYTOUT', 'Payment Timeout'), ('REFTOUT', 'Refund Timeout'), ('REFACK', 'Refund Completed'), ('ESCROW', 'Funds received and protected in escrow'), ('FUNDRE', 'Funds released to seller')], default='PYNOTSNT', max_length=20, verbose_name='payment status')),
                ('product_status', models.CharField(choices=[('PNOTSNT', 'Product Not Sent'), ('PSENT', 'Product Sent'), ('PREC', 'Product Received'), ('PNACK', 'Product Not as Advertised'), ('PACK', 'Product Verified OK'), ('PNOTREC', 'Product Not Received'), ('PNOTSNTTOUT', 'Product Not Sent Timeout'), ('PNOTRECTOUT', 'Product Not Received Timeout'), ('PRET', 'Product Returned'), ('PRETACK', 'Product Returned Received'), ('PRETTOUT', 'Product Received Timeout')], default='PNOTSNT', max_length=20, verbose_name='product status')),
                ('transaction_reference', models.CharField(db_index=True, default=transaction.models.unique_txn_ref_generator, max_length=25)),
                ('transpact_text_status', models.CharField(blank=True, max_length=500, null=True)),
                ('transpact_update_datetime', models.DateTimeField(blank=True, null=True)),
                ('transpact_scraped_datetime', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('friend_price', models.FloatField(blank=True, help_text='Special price for friends. If not set, regular price applies to all.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('deposit', models.FloatField(default=0, help_text='Deposit required from non-friends', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('friend_deposit', models.FloatField(blank=True, help_text='Special deposit for friends. If not set, regular deposit applies to all.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('delivery_distance_km', models.PositiveIntegerField(default=10, help_text='Maximum distance in km the lender can deliver/travel', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('total_weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('current_spot_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('price_as_pct_spot_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('created', models.DateField(blank=True, editable=False)),
                ('amended', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_aggressive', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.order')),
                ('order_passive', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.order')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.product')),
                ('transaction_status_raised_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_aggressive', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_passive', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
