# Generated by Django 4.2.27 on 2026-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rental_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='checkout_condition_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_collected_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_placeholder_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_resolution_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_status',
            field=models.CharField(choices=[('DEPPEND', 'Pending hold'), ('DEPHOLD', 'Held (placeholder)'), ('DEPRETF', 'Returned in full'), ('DEPRETR', 'Returned with reduction'), ('DEPMED', 'Mediation required')], default='DEPPEND', max_length=20, verbose_name='deposit status'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='enquiry_message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_collected_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_placeholder_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='return_condition_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='payment_status',
            field=models.CharField(choices=[('PAYPEND', 'Pending capture'), ('PAYCAP', 'Captured (placeholder)'), ('PAYNA', 'Not required')], default='PAYPEND', max_length=20, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Enquiry for rental'), ('RAGR', 'Rental agreed'), ('RINT', 'Rental initiated'), ('RRTN', 'Rental returned'), ('DRET', 'Deposit returned'), ('DRED', 'Reduced deposit return agreed'), ('DMED', 'Mediation required'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='product_status',
            field=models.CharField(choices=[('CONDPEND', 'Condition evidence pending'), ('CHKVID', 'Checkout condition video added'), ('RTNVID', 'Return condition video added')], default='CONDPEND', max_length=20, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Enquiry for rental'), ('RAGR', 'Rental agreed'), ('RINT', 'Rental initiated'), ('RRTN', 'Rental returned'), ('DRET', 'Deposit returned'), ('DRED', 'Reduced deposit return agreed'), ('DMED', 'Mediation required'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
    ]
