# Generated by Django 4.2.27 on 2026-05-09 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0003_historicaltransaction_checkout_condition_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='lender_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When lender confirmed the contract', null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='lender_agreement_pending_at',
            field=models.DateTimeField(blank=True, help_text='When lender initiated agreement; awaiting their confirmation', null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='renter_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When renter confirmed the contract', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lender_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When lender confirmed the contract', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lender_agreement_pending_at',
            field=models.DateTimeField(blank=True, help_text='When lender initiated agreement; awaiting their confirmation', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='renter_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When renter confirmed the contract', null=True),
        ),
        migrations.CreateModel(
            name='TransactionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('is_negative', models.BooleanField(default=False, help_text='True if feedback is negative (for non-site payments)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('left_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_left', to=settings.AUTH_USER_MODEL)),
                ('left_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='transaction.transaction')),
            ],
        ),
    ]
