# Generated by Django 4.2.27 on 2026-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_historicaltransaction_lender_agreed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_handling',
            field=models.CharField(choices=[('HELD', 'Held (no collection)'), ('HELD_RTRN', 'Held (to be collected)'), ('TAKEN_HELD', 'Taken and held'), ('TAKEN_RTRN', 'Taken and returned at end')], default='HELD', help_text='How deposit is collected and managed', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='lender_kyc_verified',
            field=models.BooleanField(default=False, help_text='Whether lender has completed required KYC verification'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='renter_kyc_verified',
            field=models.BooleanField(default=False, help_text='Whether renter has completed required KYC verification'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='requires_kyc',
            field=models.BooleanField(default=False, help_text='Whether KYC verification is required for this high-risk rental'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='requires_kyc_message',
            field=models.TextField(blank=True, help_text='Message about why KYC is required', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_handling',
            field=models.CharField(choices=[('HELD', 'Held (no collection)'), ('HELD_RTRN', 'Held (to be collected)'), ('TAKEN_HELD', 'Taken and held'), ('TAKEN_RTRN', 'Taken and returned at end')], default='HELD', help_text='How deposit is collected and managed', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lender_kyc_verified',
            field=models.BooleanField(default=False, help_text='Whether lender has completed required KYC verification'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='renter_kyc_verified',
            field=models.BooleanField(default=False, help_text='Whether renter has completed required KYC verification'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requires_kyc',
            field=models.BooleanField(default=False, help_text='Whether KYC verification is required for this high-risk rental'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requires_kyc_message',
            field=models.TextField(blank=True, help_text='Message about why KYC is required', max_length=500),
        ),
    ]
