# Generated by Django 4.2.27 on 2026-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_historicaltransaction_deposit_handling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_card_setup_status',
            field=models.CharField(choices=[('NONE', 'No deposit card on file'), ('READY', 'Deposit card ready')], default='NONE', help_text='Placeholder status for renter deposit card setup via Stripe Connect', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_cardholder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_collection_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_collection_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_collection_status',
            field=models.CharField(choices=[('NOT_RUN', 'Not run'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='NOT_RUN', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_test_hold_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_test_hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_test_hold_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_test_hold_status',
            field=models.CharField(choices=[('NOT_RUN', 'Not run'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='NOT_RUN', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_card_setup_status',
            field=models.CharField(choices=[('NONE', 'No deposit card on file'), ('READY', 'Deposit card ready')], default='NONE', help_text='Placeholder status for renter deposit card setup via Stripe Connect', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_cardholder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_collection_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_collection_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_collection_status',
            field=models.CharField(choices=[('NOT_RUN', 'Not run'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='NOT_RUN', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_test_hold_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_test_hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_test_hold_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_test_hold_status',
            field=models.CharField(choices=[('NOT_RUN', 'Not run'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='NOT_RUN', max_length=10),
        ),
    ]
