# Generated by Django 4.2.27 on 2026-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_historicaltransaction_deposit_card_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentMethod ID for stored card', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, help_text='Stripe SetupIntent ID for card tokenization', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentMethod ID for stored card', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, help_text='Stripe SetupIntent ID for card tokenization', max_length=100),
        ),
    ]
