# Generated by Django 4.2.27 on 2026-05-11

import common.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_historicaltransaction_stripe_payment_method_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmessageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.helpers.RandomFileName('images/txn_msg/')),
        ),
        migrations.AddField(
            model_name='transactionmessageimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=common.helpers.RandomFileName('videos/txn_msg/')),
        ),
    ]
