# Generated by Django 4.2.27 on 2026-05-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transactionmessageimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for reusable payment methods', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for reusable payment methods', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='deposit_card_setup_status',
            field=models.CharField(choices=[('NONE', 'No deposit card on file'), ('READY', 'Deposit card ready'), ('FAILED', 'Card setup failed')], default='NONE', help_text='Placeholder status for borrower deposit card setup via Stripe Connect', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit_card_setup_status',
            field=models.CharField(choices=[('NONE', 'No deposit card on file'), ('READY', 'Deposit card ready'), ('FAILED', 'Card setup failed')], default='NONE', help_text='Placeholder status for borrower deposit card setup via Stripe Connect', max_length=10),
        ),
    ]
