# Generated by Django 4.2.27 on 2026-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_add_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Enquiry for rental'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('RCOMP', 'Rental process fully completed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Enquiry for rental'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('RCOMP', 'Rental process fully completed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Enquiry for rental'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('RCOMP', 'Rental process fully completed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Enquiry for rental'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('RCOMP', 'Rental process fully completed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
    ]
