# Generated by Django 4.2.27 on 2026-05-12 21:03

from django.db import migrations


def migrate_transaction_statuses(apps, schema_editor):
    """Migrate old transaction status values to new ones."""
    Transaction = apps.get_model('transaction', 'Transaction')
    HistoricalTransaction = apps.get_model('transaction', 'HistoricalTransaction')
    
    # Status mapping: old status code -> new status code
    status_mapping = {
        'RINT': 'RONG',        # RENTAL_INITIATED -> RENTAL_ONGOING
        'RRTN': 'RRTDPEND',    # RENTAL_RETURNED -> RENTAL_RETURNED_DEPOSIT_PENDING
        'DRET': 'RRTDRET',     # DEPOSIT_RETURNED -> RENTAL_RETURNED_DEPOSIT_RETURNED
        'DRED': 'RRTDRET',     # DEPOSIT_REDUCED -> RENTAL_RETURNED_DEPOSIT_RETURNED
    }
    
    # Update Transaction table
    for old_status, new_status in status_mapping.items():
        Transaction.objects.filter(transaction_status=old_status).update(
            transaction_status=new_status
        )
        Transaction.objects.filter(prev_transaction_status=old_status).update(
            prev_transaction_status=new_status
        )
    
    # Update HistoricalTransaction table (for audit trail)
    for old_status, new_status in status_mapping.items():
        HistoricalTransaction.objects.filter(transaction_status=old_status).update(
            transaction_status=new_status
        )
        HistoricalTransaction.objects.filter(prev_transaction_status=old_status).update(
            prev_transaction_status=new_status
        )


def reverse_transaction_statuses(apps, schema_editor):
    """Reverse the migration if needed."""
    Transaction = apps.get_model('transaction', 'Transaction')
    HistoricalTransaction = apps.get_model('transaction', 'HistoricalTransaction')
    
    # Reverse mapping: new status code -> old status code
    reverse_mapping = {
        'RONG': 'RINT',
        'RRTDPEND': 'RRTN',
        'RRTDRET': 'DRET',
    }
    
    # Update Transaction table
    for new_status, old_status in reverse_mapping.items():
        Transaction.objects.filter(transaction_status=new_status).update(
            transaction_status=old_status
        )
        Transaction.objects.filter(prev_transaction_status=new_status).update(
            prev_transaction_status=old_status
        )
    
    # Update HistoricalTransaction table
    for new_status, old_status in reverse_mapping.items():
        HistoricalTransaction.objects.filter(transaction_status=new_status).update(
            transaction_status=old_status
        )
        HistoricalTransaction.objects.filter(prev_transaction_status=new_status).update(
            prev_transaction_status=old_status
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_update_transaction_statuses'),
    ]

    operations = [
        migrations.RunPython(migrate_transaction_statuses, reverse_transaction_statuses),
    ]
