# Generated by Django 4.2.27 on 2026-05-14 09:51

import common.helpers
from django.db import migrations, models
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_historicaltransactionmessage_is_system_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmessageimage',
            name='video_raw',
            field=models.FileField(blank=True, help_text='Raw/uncompressed video archive for verification purposes. Chain of custody.', null=True, upload_to=common.helpers.RandomFileName('videos/txn_msg_raw/')),
        ),
        migrations.AlterField(
            model_name='transactionmessageimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Max 5 MB', null=True, upload_to=common.helpers.RandomFileName('images/txn_msg/'), validators=[transaction.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='transactionmessageimage',
            name='video',
            field=models.FileField(blank=True, help_text='Max 50 MB. Optimized/display version.', null=True, upload_to=common.helpers.RandomFileName('videos/txn_msg/'), validators=[transaction.models.validate_video_size]),
        ),
    ]
