# Generated by Django 4.2.27 on 2026-05-30 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_transaction_deposit_proposal_iteration_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='delivery_cost',
            field=models.FloatField(default=0, help_text='Computed delivery cost charged for this transaction', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='rentalution_fee',
            field=models.FloatField(default=0, help_text='Computed Rentalution fee charged for this transaction', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_cost',
            field=models.FloatField(default=0, help_text='Computed delivery cost charged for this transaction', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rentalution_fee',
            field=models.FloatField(default=0, help_text='Computed Rentalution fee charged for this transaction', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
