# Generated by Django 4.2.27 on 2026-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_historicaltransaction_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_collection_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_collection_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_collection_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_collection_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
