# Generated by Django 4.2.27 on 2026-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0023_historicaltransaction_payment_collection_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='feedback_window_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='feedback_window_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Rental discussion'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('FB1SIDE', 'One-sided feedback submitted'), ('RCOMP', 'Rental process completed (mutual feedback)'), ('RCOMP1S', 'Rental process completed (one-sided feedback)'), ('RCMPNFB', 'Rental process completed (feedback window expired)'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Rental discussion'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('FB1SIDE', 'One-sided feedback submitted'), ('RCOMP', 'Rental process completed (mutual feedback)'), ('RCOMP1S', 'Rental process completed (one-sided feedback)'), ('RCMPNFB', 'Rental process completed (feedback window expired)'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Rental discussion'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('FB1SIDE', 'One-sided feedback submitted'), ('RCOMP', 'Rental process completed (mutual feedback)'), ('RCOMP1S', 'Rental process completed (one-sided feedback)'), ('RCMPNFB', 'Rental process completed (feedback window expired)'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Rental discussion'), ('RAGR', 'Rental agreed'), ('RDAYAWV', 'Rental day, awaiting verification'), ('RONG', 'Rental ongoing'), ('RRTDAYAWV', 'Rental return day, awaiting verification'), ('RRTDPEND', 'Rental returned, deposit return pending'), ('RRTDRET', 'Rental returned, deposit returned'), ('RRTDCON', 'Rental returned, deposit contested'), ('AWFB', 'Awaiting feedback'), ('FB1SIDE', 'One-sided feedback submitted'), ('RCOMP', 'Rental process completed (mutual feedback)'), ('RCOMP1S', 'Rental process completed (one-sided feedback)'), ('RCMPNFB', 'Rental process completed (feedback window expired)'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Dispute requested')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
    ]
