# Generated by Django 4.2.27 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0023_historicaltransaction_payment_collection_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_object_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending')], max_length=10)),
                ('failure_point', models.CharField(choices=[('card_setup', 'Card setup'), ('deposit_auth', 'Deposit authorization'), ('rental_capture', 'Rental capture'), ('deposit_settlement', 'Deposit settlement'), ('verification_charge', 'Verification charge')], max_length=32)),
                ('card_brand', models.CharField(blank=True, max_length=40)),
                ('card_funding', models.CharField(blank=True, max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='gbp', max_length=8)),
                ('error_message', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='payment_attempts', to='transaction.transaction')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
