# Generated by Django 4.2.27 on 2026-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0025_historicaltransaction_contract_counterparty_reminder_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='deposit_status',
            field=models.CharField(choices=[('DEPPEND', 'Pending'), ('DEPHOLD', 'Held'), ('DEPRETF', 'Returned in full'), ('DEPRETR', 'Returned with reduction'), ('DEPMED', 'Mediation')], default='DEPPEND', max_length=20, verbose_name='deposit status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='payment_status',
            field=models.CharField(choices=[('PAYPEND', 'Pending'), ('PAYCAP', 'Captured'), ('PAYNA', 'Not required')], default='PAYPEND', max_length=20, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='product_status',
            field=models.CharField(choices=[('CONDPEND', 'Condition pending'), ('CHKVID', 'Checkout video added'), ('RTNVID', 'Return video added')], default='CONDPEND', max_length=20, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit_status',
            field=models.CharField(choices=[('DEPPEND', 'Pending'), ('DEPHOLD', 'Held'), ('DEPRETF', 'Returned in full'), ('DEPRETR', 'Returned with reduction'), ('DEPMED', 'Mediation')], default='DEPPEND', max_length=20, verbose_name='deposit status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('PAYPEND', 'Pending'), ('PAYCAP', 'Captured'), ('PAYNA', 'Not required')], default='PAYPEND', max_length=20, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_status',
            field=models.CharField(choices=[('CONDPEND', 'Condition pending'), ('CHKVID', 'Checkout video added'), ('RTNVID', 'Return video added')], default='CONDPEND', max_length=20, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
    ]
