# Generated by Django 4.2.27 on 2026-06-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0026_alter_historicaltransaction_deposit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_card_funding',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='deposit_card_funding',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
