# Generated by Django 4.2.27 on 2026-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0029_disputecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('DDEC', 'Dispute decision reached'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('DDEC', 'Dispute decision reached'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prev_transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('DDEC', 'Dispute decision reached'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='previous transaction status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('RENQ', 'Discussion'), ('RAGR', 'Agreement'), ('RDAYAWV', 'Checkout verification'), ('RONG', 'Ongoing'), ('RRTDAYAWV', 'Return verification'), ('RRTDPEND', 'Deposit review'), ('RRTDRET', 'Deposit returned'), ('RRTDCON', 'Deposit contested'), ('AWFB', 'Feedback'), ('FB1SIDE', 'Feedback'), ('RCOMP', 'Completed'), ('RCOMP1S', 'Completed'), ('RCMPNFB', 'Closed'), ('DDEC', 'Dispute decision reached'), ('CREQ', 'Cancellation requested'), ('CACK', 'Cancelled'), ('DREQ', 'Mediation')], default='RENQ', max_length=20, verbose_name='transaction status'),
        ),
    ]
