# Generated by Django 4.2.27 on 2026-06-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0030_alter_historicaltransaction_prev_transaction_status_and_more'),
        ('transaction', '0030_disputecase_final_statements'),
    ]

    operations = [
    ]
