# Generated by Django 4.2.27 on 2026-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0032_disputecase_notes_and_private_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransactionmessage',
            name='private_to_sender',
            field=models.BooleanField(default=False, help_text='If true, only the sender and admin should be able to see this message on the transaction view.'),
        ),
    ]
