# Generated by Django 4.2.27 on 2026-06-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_paymentattempt'),
        ('transaction', '0033_alter_historicaltransactionmessage_private_to_sender'),
    ]

    operations = [
    ]
