# Generated by Django 4.2.27 on 2026-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0034_merge_20260616_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
