# Generated by Codex on 2026-08-05

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0036_alter_disputecase_id_alter_historicaltransaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmessageimage',
            name='transaction',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=deletion.CASCADE,
                related_name='evidence_items',
                to='transaction.transaction',
            ),
        ),
    ]
