# Generated by Django 4.2.27 on 2026-09-12 20:10

import common.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0037_transactionmessageimage_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmessageimage',
            name='preview_status',
            field=models.CharField(choices=[('pending', 'Preparing'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Unavailable')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='transactionmessageimage',
            name='preview_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionmessageimage',
            name='video_preview',
            field=models.FileField(blank=True, upload_to=common.helpers.RandomFileName('videos/txn_preview/')),
        ),
    ]
