org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStore=/home/neil/Projects/sharing-hub/sharing_hub_mobile/android/certs/gradle-cacerts-full.jks -Djavax.net.ssl.trustStorePassword=changeit
android.useAndroidX=true
