# Generated by Django 4.2.27 on 2026-07-09 16:40

import common.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0029_alter_bestpricedforcategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.helpers.RandomFileName('images/product_drafts/'))),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('ready', 'Ready'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_drafts', to='common.category')),
                ('published_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_drafts', to='common.product')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
