"""
Django settings for sharing_hub project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SHARING_HUB_SECRET_KEY','')

ALLOWED_HOSTS = []

# NPD - added
LOGIN_REDIRECT_URL = "my_sharing_hub:dashboard"
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')
# NPD - finished

# Application definition

INSTALLED_APPS = [
    'haystack',
    'navigation.apps.NavigationConfig',
    'admin_tools.apps.AdminToolsConfig',
    'account.apps.AccountConfig',
    'common.apps.CommonConfig',
    'my_sharing_hub.apps.MySharingHubConfig',
    'transaction.apps.TransactionConfig',
    'friends.apps.FriendsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'cookielaw',
    'sorl.thumbnail',
    'simple_history',
    'django.contrib.humanize',
    # 'django_otp',
    # 'django_otp.plugins.otp_totp',
    'admin_honeypot',
    'memcache_status',
    'django_summernote',
    # 'floppyforms',
    # 'material',
    # 'material.frontend',
]

MIDDLEWARE = [
    'common.middlewares.AjaxMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'sharing_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 
            os.path.join(BASE_DIR, 'sharing_hub/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sharing_hub.context_processors.from_settings',
                'sharing_hub.context_processors.top_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'sharing_hub.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'sharing_hub',
#         'USER': 'sharing_hub',
#         'PASSWORD': '9bNi8TlgoXp88fds',
#         'HOST': 'localhost', 
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# TODO: not valid for PROD
# https://django-haystack.readthedocs.io/en/master/tutorial.html
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}


# for two factor authentication of Admin
# OTP_TOTP_ISSUER = 'SharingHub'

# Celery rabbitMQ 
CELERY_BROKER_URL = 'amqp://localhost'
# Celery redis
# CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"

BOOTSTRAP4 = {
    'horizontal_label_class': 'col-md-2',
    'horizontal_field_class': 'col-md-10'
}


# Transpact settings
TRANSPACT_WSDL = 'https://www.transpact.com/SecurePartner/Partner.asmx?WSDL'
TRANSPACT_PARTNER_USERNAME = 'neil.daniels@sharing-hub.com'
TRANSPACT_PARTNER_PASSWORD = '10mC9wRrX'