# Generated by Django 4.2.27 on 2026-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
