# Generated by Django 4.2.27 on 2026-10-09 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0031_orderimage_processing_status'),
        ('navigation', '0004_alter_categorysuggestion_id_alter_searchhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysuggestion',
            name='duplicate_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='normalized_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='pipeline_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='pipeline_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='policy_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='processing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='proposed_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='proposed_image_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='proposed_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_category_suggestions', to='common.category'),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='published_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_from_suggestions', to='common.category'),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='quality_review',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_category_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorysuggestion',
            name='status',
            field=models.CharField(choices=[('NEW', 'Queued'), ('SCREENING', 'AI screening'), ('DUPLICATE', 'Possible duplicate'), ('POLICY_REJECTED', 'Not suitable'), ('MANUAL_REVIEW', 'Needs manual AI review'), ('ASSET_REVIEW', 'Ready for staff image generation'), ('GENERATING', 'Generating catalogue image'), ('QUALITY_REVIEW', 'AI quality review'), ('ADMIN_REVIEW', 'Ready for admin review'), ('FAILED', 'Automation failed'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='CategorySuggestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_suggestions/generated/')),
                ('prompt', models.TextField(blank=True, default='')),
                ('review', models.JSONField(blank=True, default=dict)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='navigation.categorysuggestion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
