# Generated by Django 4.2.27 on 2026-10-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_categorytaxonomyrecommendation_implementation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytaxonomyrecommendation',
            name='recommendation_type',
            field=models.CharField(
                choices=[
                    ('MISSING', 'Missing category'),
                    ('DUPLICATE', 'Possible duplicate / merge'),
                    ('MOVE', 'Move in tree'),
                    ('SPLIT', 'Split broad category'),
                    ('RETIRE', 'Retire thin category'),
                    ('ATTRIBUTE', 'Add a browse attribute'),
                    ('KEEP', 'Keep as-is observation'),
                ],
                max_length=12,
            ),
        ),
    ]
