org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStore=/home/neil/Projects/rentalution/rentalution_mobile/android/certs/gradle-cacerts-full.jks -Djavax.net.ssl.trustStorePassword=changeit
android.useAndroidX=true
# Enable Flutter's built-in Kotlin support for future compatibility.
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
